déclencheur:

- principal
pool:
  vmImage: ubuntu-lastest
variables:
  buildConfiguration:  .'Release'
steps:
  - script: dotnet build --configuration  $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

#pool: MyAgentPool
#steps:
#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'build'
#- bash: echo hello world
